apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: microservices-demo
data:
  # Development-specific configuration with external Ollama
  GIN_MODE: "debug"
  LOG_LEVEL: "debug"
  
  # Development URLs - use internal service names for pod-to-pod communication
  API_SERVER_URL: "http://dev-api-server-service:8081"
  FRONTEND_URL: "http://dev-frontend-service:8080"
  
  # External Ollama configuration for development
  # Update this to your external Ollama server IP/hostname
  OLLAMA_URL: "http://192.168.1.100:11434"  # Example external server
  MCP_TIMEOUT: "90s"  # Slightly longer for network calls
  
  # Development job settings with external AI
  MAX_CONCURRENT_JOBS: "5"  # Can handle more with external AI
  JOB_TIMEOUT: "240s"  # Account for network latency
  
  # Fix RabbitMQ service name for development environment
  RABBITMQ_HOST: "dev-rabbitmq-service"
