apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-server
  namespace: microservices-demo
spec:
  replicas: 1  # Single replica for development
  template:
    spec:
      containers:
        - name: api-server
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "200m"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: research-agent
  namespace: microservices-demo
spec:
  replicas: 1  # Single replica for development
  template:
    spec:
      containers:
        - name: research-agent
          resources:
            requests:
              memory: "128Mi"  # Less memory needed without local AI
              cpu: "100m"
            limits:
              memory: "256Mi"  # Reduced since AI is external
              cpu: "500m"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: microservices-demo
spec:
  replicas: 1  # Single replica for development
  template:
    spec:
      containers:
        - name: frontend
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "200m"
