apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-server
  namespace: microservices-demo
spec:
  template:
    spec:
      containers:
        - name: api-server
          resources:
            requests:
              memory: "256Mi"
              cpu: "200m"
            limits:
              memory: "512Mi"
              cpu: "1000m"
          env:
            - name: GOGC
              value: "100"  # Optimize garbage collection for production
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: research-agent
  namespace: microservices-demo
spec:
  template:
    spec:
      containers:
        - name: research-agent
          resources:
            requests:
              memory: "512Mi"  # Less memory needed without local AI
              cpu: "300m"
            limits:
              memory: "1Gi"    # Reduced since AI is external
              cpu: "1500m"
          env:
            - name: GOGC
              value: "100"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: microservices-demo
spec:
  template:
    spec:
      containers:
        - name: frontend
          resources:
            requests:
              memory: "256Mi"
              cpu: "200m"
            limits:
              memory: "512Mi"
              cpu: "1000m"
          env:
            - name: GOGC
              value: "100"
