apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-credentials
  namespace: microservices-demo
type: Opaque
data:
  # Production credentials - base64 encoded
  # Update these with your actual production credentials
  username: cHJvZC11c2Vy  # prod-user
  password: cHJvZC1wYXNzd29yZA==  # prod-password
