apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: microservices-demo
data:
  # Development-specific configuration
  GIN_MODE: "debug"
  LOG_LEVEL: "debug"
  
  # Development URLs - use internal service names for pod-to-pod communication
  API_SERVER_URL: "http://dev-api-server-service:8081"
  FRONTEND_URL: "http://dev-frontend-service:8080"
  
  # Development job settings
  MAX_CONCURRENT_JOBS: "3"  # Lower for development
  JOB_TIMEOUT: "180s"  # Reduced for development
  
  # Development AI settings
  OLLAMA_URL: "http://dev-ollama-service:11434"
  MCP_TIMEOUT: "60s"  # Reduced for development
  
  # MCP Configuration - Use test mode for development
  MCP_TEST_MODE: "true"  # Use simulated data for development
  # Note: When MCP_TEST_MODE=true, MCP server URLs are ignored
  
  # Fix RabbitMQ service name for development environment
  RABBITMQ_HOST: "dev-rabbitmq-service"
