apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: microservices-demo
data:
  # Development-specific configuration
  GIN_MODE: "debug"
  LOG_LEVEL: "debug"
  
  # Development URLs - use internal service names for pod-to-pod communication
  API_SERVER_URL: "http://dev-api-server-service:8081"
  FRONTEND_URL: "http://dev-frontend-service:8080"
  
  # Development job settings
  MAX_CONCURRENT_JOBS: "5"  # Lower for development
  
  # Fix RabbitMQ service name for development environment
  RABBITMQ_HOST: "dev-rabbitmq-service"
