apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: microservices-demo
data:
  # Production configuration
  GIN_MODE: "release"
  LOG_LEVEL: "info"
  
  # Production URLs
  API_SERVER_URL: "http://api.microservices-demo.local"
  FRONTEND_URL: "http://microservices-demo.local"
  
  # Production job settings
  MAX_CONCURRENT_JOBS: "20"
  JOB_TIMEOUT: "60s"
  
  # Health check settings
  HEALTH_CHECK_INTERVAL: "30s"
