apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: microservices-demo
data:
  # Production configuration
  GIN_MODE: "release"
  LOG_LEVEL: "info"
  
  # Production URLs
  API_SERVER_URL: "http://api.microservices-demo.local"
  FRONTEND_URL: "http://microservices-demo.local"
  
  # Production job settings
  MAX_CONCURRENT_JOBS: "10"  # Adjusted for AI workloads
  JOB_TIMEOUT: "600s"  # Increased for AI processing
  
  # Production AI settings
  OLLAMA_URL: "http://ollama-service:11434"
  MCP_TIMEOUT: "180s"  # Production timeout
  
  # Health check settings
  HEALTH_CHECK_INTERVAL: "30s"
