apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-credentials
  namespace: microservices-demo
type: Opaque
data:
  # Production credentials should be properly secured
  # These are just examples - use proper secret management
  username: cHJvZC11c2Vy  # prod-user (base64)
  password: cHJvZC1zZWN1cmUtcGFzc3dvcmQ=  # prod-secure-password (base64)
---
apiVersion: v1
kind: Secret
metadata:
  name: app-config
  namespace: microservices-demo
type: Opaque
data:
  gin-mode: cmVsZWFzZQ==  # release (base64)
