apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-server
  namespace: microservices-demo
  labels:
    app.kubernetes.io/name: microservices-demo
    app.kubernetes.io/component: api-server
    app.kubernetes.io/version: "1.0.0"
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: microservices-demo
      app.kubernetes.io/component: api-server
  template:
    metadata:
      labels:
        app.kubernetes.io/name: microservices-demo
        app.kubernetes.io/component: api-server
        app.kubernetes.io/version: "1.0.0"
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8081"
        prometheus.io/path: "/metrics"
    spec:
      containers:
        - name: api-server
          image: microservices-api-server:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8081
              protocol: TCP
          env:
            - name: RABBITMQ_USERNAME
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-credentials
                  key: username
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-credentials
                  key: password
            - name: RABBITMQ_HOST
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: RABBITMQ_HOST
            - name: RABBITMQ_PORT
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: RABBITMQ_PORT
            - name: RABBITMQ_URL
              value: "amqp://$(RABBITMQ_USERNAME):$(RABBITMQ_PASSWORD)@$(RABBITMQ_HOST):$(RABBITMQ_PORT)/"
            - name: GIN_MODE
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: GIN_MODE
            - name: LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: LOG_LEVEL
            # AI and MCP configuration for status endpoint
            - name: OLLAMA_URL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: OLLAMA_URL
            - name: OLLAMA_MODEL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: OLLAMA_MODEL
            - name: MCP_TEST_MODE
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: MCP_TEST_MODE
            - name: MCP_WEB_SERVER_URL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: MCP_WEB_SERVER_URL
            - name: MCP_GITHUB_SERVER_URL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: MCP_GITHUB_SERVER_URL
            - name: MCP_FILES_SERVER_URL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: MCP_FILES_SERVER_URL
          livenessProbe:
            httpGet:
              path: /api/health
              port: 8081
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /api/health
              port: 8081
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "500m"
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            runAsUser: 1000
            capabilities:
              drop:
                - ALL
      securityContext:
        fsGroup: 1000
