apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: microservices-demo
  labels:
    app.kubernetes.io/name: microservices-demo
    app.kubernetes.io/component: config
data:
  # RabbitMQ Configuration
  RABBITMQ_HOST: "rabbitmq-service"
  RABBITMQ_PORT: "5672"
  RABBITMQ_URL: "amqp://$(RABBITMQ_USERNAME):$(RABBITMQ_PASSWORD)@$(RABBITMQ_HOST):$(RABBITMQ_PORT)/"
  
  # Service URLs
  API_SERVER_URL: "http://api-server-service:8081"
  FRONTEND_URL: "http://frontend-service:8080"
  
  # Application Configuration
  GIN_MODE: "release"
  
  # Logging
  LOG_LEVEL: "info"
  
  # Job Runner Configuration
  JOB_TIMEOUT: "300s"  # Increased for AI processing
  MAX_CONCURRENT_JOBS: "5"  # Reduced for AI workloads
  
  # AI Research Agent Configuration
  OLLAMA_URL: "http://ollama-service:11434"
  OLLAMA_MODEL: "llama3.2"
  MCP_TIMEOUT: "120s"
  ENABLE_AI_FEATURES: "true"
  
  # MCP (Model Context Protocol) Server Configuration
  MCP_TEST_MODE: "false"  # Set to "true" for test mode with simulated data
  MCP_WEB_SERVER_URL: "http://mcp-web-service:3001"
  MCP_GITHUB_SERVER_URL: "http://mcp-github-service:3002"
  MCP_FILES_SERVER_URL: "http://mcp-files-service:3003"
  
  # Health Check Configuration
  HEALTH_CHECK_INTERVAL: "30s"
