apiVersion: apps/v1
kind: Deployment
metadata:
  name: research-agent
  namespace: microservices-demo
  labels:
    app.kubernetes.io/name: microservices-demo
    app.kubernetes.io/component: research-agent
    app.kubernetes.io/version: "1.0.0"
spec:
  replicas: 3  # Multiple replicas for load balancing
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: microservices-demo
      app.kubernetes.io/component: research-agent
  template:
    metadata:
      labels:
        app.kubernetes.io/name: microservices-demo
        app.kubernetes.io/component: research-agent
        app.kubernetes.io/version: "1.0.0"
      annotations:
        prometheus.io/scrape: "false"  # Research agent doesn't expose HTTP metrics
    spec:
      containers:
        - name: research-agent
          image: microservices-job-runner:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: RABBITMQ_USERNAME
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-credentials
                  key: username
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-credentials
                  key: password
            - name: RABBITMQ_HOST
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: RABBITMQ_HOST
            - name: RABBITMQ_PORT
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: RABBITMQ_PORT
            - name: RABBITMQ_URL
              value: "amqp://$(RABBITMQ_USERNAME):$(RABBITMQ_PASSWORD)@$(RABBITMQ_HOST):$(RABBITMQ_PORT)/"
            - name: LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: LOG_LEVEL
            - name: JOB_TIMEOUT
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: JOB_TIMEOUT
            - name: MAX_CONCURRENT_JOBS
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: MAX_CONCURRENT_JOBS
            # AI-specific configuration
            - name: OLLAMA_URL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: OLLAMA_URL
            - name: OLLAMA_MODEL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: OLLAMA_MODEL
            - name: MCP_TIMEOUT
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: MCP_TIMEOUT
            - name: ENABLE_AI_FEATURES
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: ENABLE_AI_FEATURES
          # No HTTP probes for research agent, but we can check process health
          livenessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - "pgrep -f main > /dev/null"
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 3
          readinessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - "pgrep -f main > /dev/null"
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          resources:
            requests:
              memory: "512Mi"  # Increased for AI workloads
              cpu: "200m"
            limits:
              memory: "1Gi"    # More memory for AI processing
              cpu: "1000m"
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            runAsUser: 1000
            capabilities:
              drop:
                - ALL
      securityContext:
        fsGroup: 1000
