apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: microservices-demo-base
  annotations:
    config.kubernetes.io/local-config: "true"

resources:
  - namespace.yaml
  - secrets.yaml
  - configmap.yaml
  - rabbitmq-service.yaml
  - rabbitmq-deployment.yaml
  - api-server-service.yaml
  - api-server-deployment.yaml
  - job-runner-deployment.yaml
  - frontend-service.yaml
  - frontend-deployment.yaml
  - ingress.yaml
  # Ollama resources (comment out if using external Ollama)
  # - ollama-pvc.yaml
  # - ollama-deployment.yaml
  # - ollama-service.yaml

labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/name: microservices-demo
      app.kubernetes.io/managed-by: kustomize

images:
  - name: microservices-api-server
    newName: localhost:5000/microservices-api-server
    newTag: latest
  - name: microservices-job-runner
    newName: localhost:5000/microservices-job-runner
    newTag: latest
  - name: microservices-frontend
    newName: localhost:5000/microservices-frontend
    newTag: latest
  - name: ollama/ollama
    newName: ollama/ollama
    newTag: latest

namespace: microservices-demo
