apiVersion: apps/v1
kind: Deployment
metadata:
  name: mcp-web-server
  namespace: microservices-demo
  labels:
    app.kubernetes.io/name: microservices-demo
    app.kubernetes.io/component: mcp-web-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: microservices-demo
      app.kubernetes.io/component: mcp-web-server
  template:
    metadata:
      labels:
        app.kubernetes.io/name: microservices-demo
        app.kubernetes.io/component: mcp-web-server
    spec:
      containers:
        - name: mcp-web-server
          image: mcp-web-server:latest  # Your MCP web search server image
          ports:
            - containerPort: 3001
          env:
            - name: PORT
              value: "3001"
            - name: SEARCH_API_KEY
              valueFrom:
                secretKeyRef:
                  name: mcp-secrets
                  key: search-api-key
            - name: SEARCH_ENGINE
              value: "duckduckgo"  # or "google", "bing"
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /health
              port: 3001
            initialDelaySeconds: 30
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /ready
              port: 3001
            initialDelaySeconds: 5
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: mcp-web-service
  namespace: microservices-demo
  labels:
    app.kubernetes.io/name: microservices-demo
    app.kubernetes.io/component: mcp-web-server
spec:
  ports:
    - port: 3001
      targetPort: 3001
      protocol: TCP
  selector:
    app.kubernetes.io/name: microservices-demo
    app.kubernetes.io/component: mcp-web-server
