apiVersion: v1
kind: Secret
metadata:
  name: mcp-secrets
  namespace: microservices-demo
  labels:
    app.kubernetes.io/name: microservices-demo
    app.kubernetes.io/component: mcp-secrets
type: Opaque
stringData:
  # Search API credentials (choose one based on your search provider)
  search-api-key: "your-search-api-key-here"  # For Google Custom Search, Bing, etc.
  
  # GitHub API credentials
  github-token: "your-github-personal-access-token-here"
  
  # Optional: Additional API keys
  # serpapi-key: "your-serpapi-key-here"
  # openai-key: "your-openai-key-for-embeddings"
