apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-credentials
  namespace: microservices-demo
  labels:
    app.kubernetes.io/name: microservices-demo
    app.kubernetes.io/component: rabbitmq
type: Opaque
data:
  # Default credentials: guest/guest (base64 encoded)
  # In production, these should be properly secured and not stored in plain text
  username: Z3Vlc3Q=  # guest
  password: Z3Vlc3Q=  # guest
---
apiVersion: v1
kind: Secret
metadata:
  name: app-config
  namespace: microservices-demo
  labels:
    app.kubernetes.io/name: microservices-demo
    app.kubernetes.io/component: config
type: Opaque
data:
  # Application secrets (base64 encoded)
  gin-mode: cmVsZWFzZQ==  # release
