apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: microservices-demo
data:
  # External Ollama Configuration
  # Update this URL to point to your external Ollama server
  OLLAMA_URL: "http://your-ollama-server:11434"
  
  # Optional: Increase timeout for external network calls
  MCP_TIMEOUT: "180s"
  
  # Job settings optimized for external AI server
  JOB_TIMEOUT: "600s"  # Longer timeout for network calls
  MAX_CONCURRENT_JOBS: "8"  # Can handle more since no local AI overhead
